In [61]:
# Import Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
import gmaps

# Census & gmaps API Keys
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [62]:
# Store filepath in a variable
Absent_rate = "Absent_Suspension_Rate.csv"

In [63]:
#Read CSV file
Absent_rate_df = pd.read_csv(Absent_rate)

In [64]:
#Show the header
Absent_rate_df.head()

,Name,Cumulative Enrollment,Chronic absenteeism elgible enrollment,Absent Count,Absent Rate,Total Suspension,Unduplicated Count of Students Suspended,Suspension Rate,percent students one suspension,percent of students with multiple suspensions
0,ABC Unified,"21,306","21,026","1,457",6.90%,583,410,1.90%,75.90%,24.10%
1,Acton-Agua Dulce Unified,"25,196","22,918","3,554",15.50%,82,63,0.30%,79.40%,20.60%
2,Alhambra Unified,"17,485","17,210",666,3.90%,41,39,0.20%,94.90%,5.10%
3,Antelope Valley Union High,"25,491","24,523","5,417",22.10%,"3,691","2,255",8.80%,67.40%,32.60%
4,Arcadia Unified,"9,804","9,697",403,4.20%,159,128,1.30%,85.20%,14.80%

In [68]:
school_list = list(Absent_rate_df['Name'])

In [69]:
#my_phrase = "Name"
base_url='https://maps.googleapis.com/maps/api/place/textsearch/json'
params = {
    "query": 'Name',
    "key": gkey
}

requests.get(base_url, params).json()
addresses = []
for school in school_list:
    query = school + 'in Los Angeles'
    params = {
    "query": query,
    "key": gkey
    }
    response = requests.get(base_url, params).json()
    try:
        addresses.append(response['results'][0]['formatted_address'])
    except:
        addresses.append('')

In [70]:
addresses

['',
 '33792 Crown Valley Rd, Acton, CA 93510, USA',
 '',
 'Antelope Valley Union High School District, CA, USA',
 '',
 '',
 '',
 '8886 Venice Blvd, Los Angeles, CA 90034, USA',
 '',
 '',
 '',
 '',
 '28131 Livingston Ave, Valencia, CA 91355, USA',
 '14901 S Inglewood Ave, Lawndale, CA 90260, USA',
 '',
 '',
 '',
 '3145 E Garvey Ave N, West Covina, CA 91791, USA',
 '',
 '',
 '',
 '11701 Scott Ave, Whittier, CA 90604, USA',
 '45006 30th St E, Lancaster, CA 93535, USA',
 '',
 '9204 Flair Dr Suite A, El Monte, CA 91731, USA',
 '70 Olvera St, Los Angeles, CA 90012, USA',
 '',
 '5760 6th Ave, Los Angeles, CA 90043, USA',
 '',
 '',
 '',
 '753 Glendora Ave, La Puente, CA 91744, USA',
 '',
 '1800 Prospect Ave, Hermosa Beach, CA 90254, USA',
 'Hughes-elizabeth Lakes Union Elementary, CA, USA',
 '',
 '34004 128th St E, Pearblossom, CA 93553, USA',
 '',
 '44021 15th St E, Lancaster, CA 93535, USA',
 '',
 '16315 Grevillea Ave, Lawndale, CA 90260, USA',
 '',
 'Little Lake City Elementary, CA, USA',
 '',
 '500 W Temple St, Los Angeles, CA 90012, USA',
 '',
 '',
 '',
 '',
 '1700 N Sepulveda Blvd, Manhattan Beach, CA 90266, USA',
 '',
 '',
 '6410 Olcott St, Tujunga, CA 91042, USA',
 '',
 '12820 Pioneer Blvd, Norwalk, CA 90650, USA',
 '37500 50th St E, Palmdale, CA 93552, USA',
 '',
 '',
 '',
 '',
 '2410 Marine Ave, Redondo Beach, CA 90278, USA',
 '4515 Encinita Ave, Rosemead, CA 91770, USA',
 '',
 '',
 '',
 '1651 16th St, Santa Monica, CA 90404, USA',
 '',
 '115 N Ave 53, Los Angeles, CA 90042, USA',
 '4970 Huntington Dr, Los Angeles, CA 90032, USA',
 '13305 San Pedro St, Los Angeles, CA 90061, USA',
 '',
 '',
 '1905 Armacost Ave, Los Angeles, CA 90025, USA',
 '2665 Clarendon Ave, Huntington Park, CA 90255, USA',
 '701 S Catalina St A414, Los Angeles, CA 90005, USA',
 '',
 '12001 Bonavista Ln, Whittier, CA 90604, USA',
 '308 N Oxford Ave, Los Angeles, CA 90004, USA',
 '',
 '',
 '',
 '20701 Currier Rd, Walnut, CA 91789, USA',
 '',
 '150 S Burlington Ave, Los Angeles, CA 90057, USA',
 '6726 Washington Ave, Whittier, CA 90601, USA',
 'Whittier Union High School District, CA, USA',
 '',
 'Compton, CA 90222, USA',
 '']

In [72]:
Absent_rate_df['school_address'] = addresses
Absent_rate_df

,Name,Cumulative Enrollment,Chronic absenteeism elgible enrollment,Absent Count,Absent Rate,Total Suspension,Unduplicated Count of Students Suspended,Suspension Rate,percent students one suspension,percent of students with multiple suspensions,school_address
0,ABC Unified,"21,306","21,026","1,457",6.90%,583,410,1.90%,75.90%,24.10%,
1,Acton-Agua Dulce Unified,"25,196","22,918","3,554",15.50%,82,63,0.30%,79.40%,20.60%,"33792 Crown Valley Rd, Acton, CA 93510, USA"
2,Alhambra Unified,"17,485","17,210",666,3.90%,41,39,0.20%,94.90%,5.10%,
3,Antelope Valley Union High,"25,491","24,523","5,417",22.10%,"3,691","2,255",8.80%,67.40%,32.60%,"Antelope Valley Union High School District, CA..."
4,Arcadia Unified,"9,804","9,697",403,4.20%,159,128,1.30%,85.20%,14.80%,
5,Azusa Unified,"8,892","8,641",778,9.00%,476,337,3.80%,73.90%,26.10%,
6,Baldwin Park Unified,"27,278","20,740","2,434",11.70%,768,467,1.70%,69.60%,30.40%,
7,Bassett Unified,"3,814","3,723",373,10.00%,135,102,2.70%,79.40%,20.60%,"8886 Venice Blvd, Los Angeles, CA 90034, USA"
8,Bellflower Unified,"12,649","12,379","1,309",10.60%,927,602,4.80%,71.60%,28.40%,
9,Beverly Hills Unified,"4,095","4,019",364,9.10%,233,158,3.90%,73.40%,26.60%,
10,Bonita Unified,"10,747","10,420",805,7.70%,509,355,3.30%,75.20%,24.80%,
11,Burbank Unified,"15,642","15,470","1,296",8.40%,655,471,3.00%,76.20%,23.80%,
12,Castaic Union,"2,266","2,219",133,6.00%,41,33,1.50%,78.80%,21.20%,"28131 Livingston Ave, Valencia, CA 91355, USA"
13,Centinela Valley Union High,"11,065","8,739","2,727",31.20%,272,242,2.20%,90.10%,9.90%,"14901 S Inglewood Ave, Lawndale, CA 90260, USA"
14,Charter Oak Unified,"5,095","4,982",439,8.80%,251,144,2.80%,68.80%,31.30%,
15,Claremont Unified,"7,278","7,220",559,7.70%,182,132,1.80%,74.20%,25.80%,
16,Compton Unified,"25,475","24,731","3,765",15.20%,646,484,1.90%,76.70%,23.30%,
17,Covina-Valley Unified,"12,497","12,228","1,110",9.10%,599,453,3.60%,78.10%,21.90%,"3145 E Garvey Ave N, West Covina, CA 91791, USA"
18,Culver City Unified,"7,197","7,120",571,8.00%,165,121,1.70%,80.20%,19.80%,
19,Downey Unified,"22,929","22,528","2,457",10.90%,911,676,2.90%,79.60%,20.40%,
20,Duarte Unified,"9,797","4,674",417,8.90%,199,151,1.50%,78.10%,21.90%,
21,East Whittier City Elementary,"9,028","8,866",523,5.90%,221,171,1.90%,80.70%,19.30%,"11701 Scott Ave, Whittier, CA 90604, USA"
22,Eastside Union Elementary,"3,895","3,727",722,19.40%,298,202,5.20%,71.30%,28.70%,"45006 30th St E, Lancaster, CA 93535, USA"
23,El Monte City,"8,729","8,573",345,4.00%,131,94,1.10%,76.60%,23.40%,
24,El Monte Union High,"9,357","9,084","1,110",12.20%,385,286,3.10%,75.50%,24.50%,"9204 Flair Dr Suite A, El Monte, CA 91731, USA"
25,El Rancho Unified,"9,115","8,923",919,10.30%,317,232,2.50%,79.70%,20.30%,"70 Olvera St, Los Angeles, CA 90012, USA"
26,El Segundo Unified,"3,539","3,516",186,5.30%,48,43,1.20%,88.40%,11.60%,
27,Garvey Elementary,"5,224","4,859",307,6.30%,84,68,1.30%,86.80%,13.20%,"5760 6th Ave, Los Angeles, CA 90043, USA"
28,Glendale Unified,"26,886","26,608","1,731",6.50%,732,527,2.00%,77.40%,22.60%,
29,Glendora Unified,"7,632","7,540",471,6.20%,189,149,2.00%,83.90%,16.10%,
...,...,...,...,...,...,...,...,...,...,...,...
59,Pomona Unified,"25,448","24,743","3,126",12.60%,"1,331",893,3.50%,73.90%,26.10%,
60,Redondo Beach Unified,"10,149","10,040",635,6.30%,250,185,1.80%,75.70%,24.30%,"2410 Marine Ave, Redondo Beach, CA 90278, USA"
61,Rosemead Elementary,"2,559","2,535",33,1.30%,45,39,1.50%,84.60%,15.40%,"4515 Encinita Ave, Rosemead, CA 91770, USA"
62,Rowland Unified,"15,113","14,747","1,357",9.20%,421,280,1.90%,71.80%,28.20%,
63,San Gabriel Unified,"11,743","8,222",873,10.60%,190,126,1.10%,68.30%,31.70%,
64,San Marino Unified,"3,138","3,106",87,2.80%,13,10,0.30%,70.00%,30.00%,
65,Santa Monica-Malibu Unified,"11,121","11,005","1,020",9.30%,363,270,2.40%,73.30%,26.70%,"1651 16th St, Santa Monica, CA 90404, USA"
66,Saugus Union,"10,409","10,321",580,5.60%,17,12,0.10%,75.00%,25.00%,
67,SBE - Academia Avance Charter,428,416,45,10.80%,27,20,4.70%,85.00%,15.00%,"115 N Ave 53, Los Angeles, CA 90042, USA"
68,SBE - Anahuacalmecac International University ...,400,378,73,19.30%,0,0,0.00%,0.00%,0.00%,"4970 Huntington Dr, Los Angeles, CA 90032, USA"
69,SBE - Barack Obama Charter,464,445,149,33.50%,0,0,0.00%,0.00%,0.00%,"13305 San Pedro St, Los Angeles, CA 90061, USA"
70,SBE - Celerity Himalia,638,632,35,5.50%,0,0,0.00%,0.00%,0.00%,
71,SBE - Celerity Rolas,334,323,22,6.80%,0,0,0.00%,0.00%,0.00%,
72,SBE - New West Charter,842,834,20,2.40%,0,0,0.00%,0.00%,0.00%,"1905 Armacost Ave, Los Angeles, CA 90025, USA"
73,SBE - Prepa Tec Los Angeles High,246,235,57,24.30%,16,16,6.50%,100.00%,0.00%,"2665 Clarendon Ave, Huntington Park, CA 90255,..."
74,SBE - The School of Arts and Enterprise,850,822,127,15.50%,12,10,1.20%,80.00%,20.00%,"701 S Catalina St A414, Los Angeles, CA 90005,..."
75,South Pasadena Unified,"5,072","4,884",260,5.30%,66,53,1.00%,84.90%,15.10%,
76,South Whittier Elementary,"2,969","2,876",246,8.60%,69,49,1.70%,75.50%,24.50%,"12001 Bonavista Ln, Whittier, CA 90604, USA"
77,Sulphur Springs Union,"5,742","5,655",547,9.70%,77,63,1.10%,87.30%,12.70%,"308 N Oxford Ave, Los Angeles, CA 90004, USA"
78,Temple City Unified,"6,024","5,967",285,4.80%,42,37,0.60%,86.50%,13.50%,
79,Torrance Unified,"24,196","23,858","1,153",4.80%,794,569,2.40%,76.40%,23.60%,
80,Valle Lindo Elementary,"1,090","1,070",67,6.30%,20,17,1.60%,82.40%,17.60%,
81,Walnut Valley Unified,"14,700","13,722",568,4.10%,223,182,1.20%,83.50%,16.50%,"20701 Currier Rd, Walnut, CA 91789, USA"
82,West Covina Unified,"14,248","13,656","1,759",12.90%,261,182,1.30%,72.50%,27.50%,
83,Westside Union Elementary,"10,153","9,955",947,9.50%,381,266,2.60%,75.60%,24.40%,"150 S Burlington Ave, Los Angeles, CA 90057, USA"
84,Whittier City Elementary,"6,479","6,349",545,8.60%,245,158,2.40%,67.70%,32.30%,"6726 Washington Ave, Whittier, CA 90601, USA"
85,Whittier Union High,"12,354","12,050","1,494",12.40%,501,445,3.60%,88.80%,11.20%,"Whittier Union High School District, CA, USA"
86,William S. Hart Union High,"28,122","26,883","2,750",10.20%,533,450,1.60%,84.40%,15.60%,
87,Wilsona Elementary,"1,492","1,434",245,17.10%,80,55,3.70%,74.50%,25.50%,"Compton, CA 90222, USA"
88,Wiseburn Unified,"4,888","4,571",333,7.30%,60,46,0.90%,76.10%,23.90%,

In [73]:
del Absent_rate_df ['school_address']
Absent_rate_df.head()

,Name,Cumulative Enrollment,Chronic absenteeism elgible enrollment,Absent Count,Absent Rate,Total Suspension,Unduplicated Count of Students Suspended,Suspension Rate,percent students one suspension,percent of students with multiple suspensions
0,ABC Unified,"21,306","21,026","1,457",6.90%,583,410,1.90%,75.90%,24.10%
1,Acton-Agua Dulce Unified,"25,196","22,918","3,554",15.50%,82,63,0.30%,79.40%,20.60%
2,Alhambra Unified,"17,485","17,210",666,3.90%,41,39,0.20%,94.90%,5.10%
3,Antelope Valley Union High,"25,491","24,523","5,417",22.10%,"3,691","2,255",8.80%,67.40%,32.60%
4,Arcadia Unified,"9,804","9,697",403,4.20%,159,128,1.30%,85.20%,14.80%

In [76]:
Name_table = Absent_rate_df[["Name", "School Address"]]
Name_table

KeyError: "['School Address'] not in index"

In [83]:
# Store filepath in a variable
Add_schools = "School_Dist_Notin.csv"

In [84]:
#Read CSV file
Add_schools_df = pd.read_csv(Add_schools)
Add_schools_df

,Unnamed: 0,Name,School Address
0,0,ABC Unified,"16700 Norwalk Blvd, Cerritos, CA 90703"
1,2,Alhambra Unified,"1515 W Mission Rd, Alhambra, CA 91803"
2,4,Arcadia Unified,"150 S 3rd Ave., Arcadia, CA 91006"
3,5,Azusa Unified,"546 South Citrus Ave. Azusa, CA 91702-0500"
4,6,Baldwin Park Unified,"3699 Holly Ave, Baldwin Park, CA 91706"
5,8,Bellflower Unified,"16703 S. Clark Ave., Bellflower, CA 90706\n"
6,9,Beverly Hills Unified,"255 S Lasky Dr, Beverly Hills, CA 90212"
7,10,Bonita Unified,"115 W. Allen Ave., San Dimas, CA 91773"
8,11,Burbank Unified,"1900 West Olive Avenue, Burbank, CA 91506"
9,14,Charter Oak Unified,"20240 E Cienega Ave Covina, Ca 91724"
10,15,Claremont Unified,"170 W. San Jose Ave.\nClaremont, California 91711"
11,16,Compton Unified,"417 W Alondra Blvd, Compton CA 90220"
12,18,Culver City Unified,"4034 Irving Place \nCulver City, CA 90232"
13,19,Downey Unified,"11627 Brookshire Ave. Downey, CA 90241-7017"
14,20,Duarte Unified,"1620 E Huntington Dr, Duarte, CA 91010"
15,23,El Monte City,"3540 North Lexington Ave. El Monte, CA 91731-2684"
16,26,El Segundo Unified,"641 Sheldon St, El Segundo, CA 90245"
17,28,Glendale Unified,"223 North Jackson Street, Glendale, CA 91206"
18,29,Glendora Unified,"500 N. Loraine Ave., Glendora, CA 91741"
19,59,Pomona Unified,"800 S. GAREY AVE, POMONA, CA 91766"
20,62,Rowland Unified,"1830 Nogales Street\nRowland Heights, CA 91748"
21,63,San Gabriel Unified,"408 S Junipero Serra Dr, San Gabriel, CA 91776"
22,64,San Marino Unified,"1665 West Dr., San Marino, CA 91108"
23,66,Saugus Union,"24930 Avenue Stanford, Santa Clarita, CA 91355"
24,70,SBE - Celerity Himalia,"4501 Wadsworth Ave, Los Angeles, CA 90011"
25,71,SBE - Celerity Rolas,"1495 Colorado Blvd. Los Angeles, CA 90041-2366"
26,75,South Pasadena Unified,"1020 EL CENTRO ST., SOUTH PASADENA, CA 91030"
27,78,Temple City Unified,"9700 Las Tunas Drive, Temple City, CA 91780"
28,79,Torrance Unified,"2335 Plaza Del Amo\nTorrance, CA 90501"
29,80,Valle Lindo Elementary,"1431 N. CENTRAL AVE., SOUTH EL MONTE, CA 91733"
30,82,West Covina Unified,"1717 W. Merced Avenue West Covina, CA 91790"
31,86,William S. Hart Union High,"21380 Centre Pointe Parkway\nSanta Clarita, CA..."
32,88,Wiseburn Unified,"201 N Douglas St, El Segundo, CA 90245"

In [86]:
#Merge on School name 
SchoolTot_df = pd.merge(Absent_rate_df, Add_schools_df,on="Name")
SchoolTot_df.head()

,Name,Cumulative Enrollment,Chronic absenteeism elgible enrollment,Absent Count,Absent Rate,Total Suspension,Unduplicated Count of Students Suspended,Suspension Rate,percent students one suspension,percent of students with multiple suspensions,Unnamed: 0,School Address
0,ABC Unified,"21,306","21,026","1,457",6.90%,583,410,1.90%,75.90%,24.10%,0,"16700 Norwalk Blvd, Cerritos, CA 90703"
1,Alhambra Unified,"17,485","17,210",666,3.90%,41,39,0.20%,94.90%,5.10%,2,"1515 W Mission Rd, Alhambra, CA 91803"
2,Arcadia Unified,"9,804","9,697",403,4.20%,159,128,1.30%,85.20%,14.80%,4,"150 S 3rd Ave., Arcadia, CA 91006"
3,Azusa Unified,"8,892","8,641",778,9.00%,476,337,3.80%,73.90%,26.10%,5,"546 South Citrus Ave. Azusa, CA 91702-0500"
4,Baldwin Park Unified,"27,278","20,740","2,434",11.70%,768,467,1.70%,69.60%,30.40%,6,"3699 Holly Ave, Baldwin Park, CA 91706"

In [87]:
#Clean dataset- Delete unnamed 
del SchoolTot_df ['Unnamed: 0']
SchoolTot_df.head()

,Name,Cumulative Enrollment,Chronic absenteeism elgible enrollment,Absent Count,Absent Rate,Total Suspension,Unduplicated Count of Students Suspended,Suspension Rate,percent students one suspension,percent of students with multiple suspensions,School Address
0,ABC Unified,"21,306","21,026","1,457",6.90%,583,410,1.90%,75.90%,24.10%,"16700 Norwalk Blvd, Cerritos, CA 90703"
1,Alhambra Unified,"17,485","17,210",666,3.90%,41,39,0.20%,94.90%,5.10%,"1515 W Mission Rd, Alhambra, CA 91803"
2,Arcadia Unified,"9,804","9,697",403,4.20%,159,128,1.30%,85.20%,14.80%,"150 S 3rd Ave., Arcadia, CA 91006"
3,Azusa Unified,"8,892","8,641",778,9.00%,476,337,3.80%,73.90%,26.10%,"546 South Citrus Ave. Azusa, CA 91702-0500"
4,Baldwin Park Unified,"27,278","20,740","2,434",11.70%,768,467,1.70%,69.60%,30.40%,"3699 Holly Ave, Baldwin Park, CA 91706"